---
apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins2
  namespace: kube-system
subsets:
  - addresses:
      - ip: 20.0.1.12
    ports:
      - port: 8081
        name: jenkins2
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "jenkins2"
  namespace: kube-system
spec:
  ports:
    - name: "jenkins2"
      protocol: "TCP"
      port: 8081
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins2
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: jenkins.new.cloudearn.in
      http:
        paths:
          - path: /
            pathType: Prefix   # Required in v1 Ingress API
            backend:
              service:
                name: jenkins2  # Ensure it's the same as the Service name
                port:
                  number: 8081
  tls:
    - hosts:
        - jenkins.new.cloudearn.in
      secretName: build-kubernetes-new-tls

