---
apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins
  namespace: kube-system
subsets:
  - addresses:
      - ip: 20.0.1.12
    ports:
      - port: 8080
        name: jenkins
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "jenkins"
  namespace: kube-system
spec:
  ports:
    - name: "jenkins"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: jenkins.cloudearn.in
      http:
        paths:
          - path: /
            pathType: Prefix   # Required in v1 Ingress API
            backend:
              service:
                name: jenkins  # Ensure it's the same as the Service name
                port:
                  number: 8080
  tls:
    - hosts:
        - jenkins.cloudearn.in
      secretName: build-kubernetes-tls

