apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f99812b8bcd3f216 
    fsType: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: prom-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
