apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-09078997b93e24745
    fsType: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: loki-pvc
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
